version: '3.8'

services:
  # ----------------------------------- USERS SERVICE -----------------------------------

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    ports:
      - '4001:4001'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=kargo_user
      - DB_PASSWORD=kargo_pass
      - DB_DATABASE=kargo_db
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=3600
      - PORT=4001
      - HOST=localhost
      # - AUTH_SERVICE_HOST=auth
      # - AUTH_SERVICE_PORT=4002
    depends_on:
      - db
    command: npm run start:dev users
    networks:
      - kargo-network
    volumes:
      - ./apps/users:/usr/src/app/apps/users
      - ./libs:/usr/src/app/libs

  # ----------------------------------- AUTH SERVICE -----------------------------------
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    ports:
      - '4002:4002'
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=3600
      - PORT=4002
      - HOST=localhost
      - USERS_SERVICE_HOST=users
      - USERS_SERVICE_PORT=4001

    depends_on:
      - users
    command: npm run start:dev auth
    networks:
      - kargo-network
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth

  # ----------------------------------- GATEWAY API SERVICE -----------------------------------
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - USERS_SERVICE_HOST=users
      - USERS_SERVICE_PORT=4001
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=4002
      - PORT=4000
      - HOST=localhost

      - MINIO_ENDPOINT=minio
      - MINIO_BUCKET=kargo-files
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_REGION=us-east-1

    depends_on:
      - users
      - auth
    command: npm run start:dev
    networks:
      - kargo-network
    volumes:
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway
  # Uncomment the following lines if you have a reservations service

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kargo_db
      MYSQL_USER: kargo_user
      MYSQL_PASSWORD: kargo_pass
    ports:
      - '3307:3308'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kargo-network

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio-data:/data
    networks:
      - kargo-network

networks:
  kargo-network:
    driver: bridge
volumes:
  db_data:
    driver: local
