export const mockTrips = [
  {
    id: 1,
    transporter: {
      name: "Youssef B.",
      avatarUrl: "https://i.pravatar.cc/150?u=youssef",
      rating: 4.9,
      trips: 23,
    },
    origin: "Casablanca",
    destination: "Marrakech",
    date: "July 15, 2024",
    price: "150 MAD",
    capacity: "Trunk space available",
    vehicle: "Sedan",
  },
  {
    id: 2,
    transporter: {
      name: "Fatima Z.",
      avatarUrl: "https://i.pravatar.cc/150?u=fatima",
      rating: 5.0,
      trips: 15,
    },
    origin: "Rabat",
    destination: "Tangier",
    date: "July 16, 2024",
    price: "120 MAD",
    capacity: "2 large boxes",
    vehicle: "SUV",
  },
  {
    id: 3,
    transporter: {
      name: "Mehdi A.",
      avatarUrl: "https://i.pravatar.cc/150?u=mehdi",
      rating: 4.8,
      trips: 41,
    },
    origin: "Agadir",
    destination: "Essaouira",
    date: "July 18, 2024",
    price: "80 MAD",
    capacity: "Full pickup bed",
    vehicle: "Pickup Truck",
  },
  {
    id: 4,
    transporter: {
      name: "Amina K.",
      avatarUrl: "https://i.pravatar.cc/150?u=amina2",
      rating: 4.7,
      trips: 8,
    },
    origin: "Casablanca",
    destination: "Marrakech",
    date: "July 15, 2024",
    price: "140 MAD",
    capacity: "1 large suitcase",
    vehicle: "Hatchback",
  },
  {
    id: 5,
    transporter: {
      name: "Omar S.",
      avatarUrl: "https://i.pravatar.cc/150?u=omar",
      rating: 4.9,
      trips: 31,
    },
    origin: "Casablanca",
    destination: "Marrakech",
    date: "July 15, 2024",
    price: "160 MAD",
    capacity: "Backseat space",
    vehicle: "Crossover",
  },
];

export const mockDemands = [
  {
    id: 1,
    sender: {
      name: "Amina K.",
      avatarUrl: "https://i.pravatar.cc/150?u=amina",
      rating: 5.0,
      shipments: 5,
    },
    origin: "Fes",
    destination: "Meknes",
    date: "Flexible",
    budget: "70 MAD",
    package: { type: "Small Box", details: "30x30x30cm, ~2kg" },
  },
  {
    id: 2,
    sender: {
      name: "Karim S.",
      avatarUrl: "https://i.pravatar.cc/150?u=karim",
      rating: 4.9,
      shipments: 12,
    },
    origin: "Tangier",
    destination: "Casablanca",
    date: "July 20, 2024",
    budget: "200 MAD",
    package: { type: "Artwork", details: "Fragile, 100x80cm canvas" },
  },
  {
    id: 3,
    sender: {
      name: "Layla E.",
      avatarUrl: "https://i.pravatar.cc/150?u=layla",
      rating: 5.0,
      shipments: 2,
    },
    origin: "Marrakech",
    destination: "Ouarzazate",
    date: "July 22, 2024",
    budget: "100 MAD",
    package: { type: "Luggage", details: "1 large suitcase" },
  },
  {
    id: 4,
    sender: {
      name: "Samir T.",
      avatarUrl: "https://i.pravatar.cc/150?u=samir",
      rating: 4.8,
      shipments: 8,
    },
    origin: "Fes",
    destination: "Meknes",
    date: "Flexible",
    budget: "60 MAD",
    package: { type: "Documents", details: "A4 Envelope" },
  },
  {
    id: 5,
    sender: {
      name: "Nadia F.",
      avatarUrl: "https://i.pravatar.cc/150?u=nadia",
      rating: 5.0,
      shipments: 3,
    },
    origin: "Fes",
    destination: "Meknes",
    date: "Flexible",
    budget: "90 MAD",
    package: { type: "Laptop Bag", details: "Standard size, ~3kg" },
  },
];
